[package]
name = "kalendarilo"
version = "0.2.0"
publish = false
edition = "2024"
rust-version = "1.91.1"
authors = ["SyiMyuZya <syimyuzya@gmail.com>"]
license = "GPL-3.0-only"
description = "Calculate Chinese lunisolar calendar using accurate astronomical data"

[dependencies]
